# Generated by Django 3.0.3 on 2020-03-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=80, verbose_name='Nome do produto')),
                ('quant_product', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desc_product', models.CharField(max_length=150, verbose_name='Descrição do produto')),
                ('price_product', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Custo do produto (R$)')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_products', to='establishment.Establishment', verbose_name='Estabelecimento produto')),
            ],
        ),
    ]
