# Generated by Django 3.0.3 on 2020-03-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True, verbose_name='Custo do produto (R$)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quant_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade do produto'),
        ),
    ]
