# Generated by Django 3.0.3 on 2020-03-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_establishment', models.CharField(max_length=150, verbose_name='Nome do Estabelecimento')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=50, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=6, verbose_name='Número')),
                ('cnpj', models.CharField(blank=True, max_length=15, null=True, verbose_name='CNPJ')),
            ],
        ),
    ]
