# Generated by Django 3.0.4 on 2020-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True, verbose_name='Email do estabelecimento'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Senha'),
            preserve_default=False,
        ),
    ]
