# Generated by Django 3.0.4 on 2020-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_auto_20200320_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email do estabelecimento'),
        ),
    ]
