# Generated by Django 3.0.3 on 2020-03-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=80, verbose_name='Nome do Estabelecimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email do cliente')),
                ('cell_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular')),
                ('card_points', models.IntegerField(max_length=2, null=True, verbose_name='Pontos na carteira')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_client', to='establishment.Establishment', verbose_name='Estabelecimento')),
            ],
        ),
    ]
