# Generated by Django 3.0.3 on 2020-03-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='card_points',
            field=models.IntegerField(null=True, verbose_name='Pontos na carteira'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name_client',
            field=models.CharField(max_length=80, verbose_name='Nome do Cliente'),
        ),
    ]
